### PR TITLE
Fixed initial nginx problems

### PR DESCRIPTION
**Pull request by BClark09**
- User input is now done by whiptail.
- Checks for failures are put into place for key generation.
- A confirmation of settings chosen is presented before any changes are made.
- dig retrieves the last IP in it's lookup. Which should solve problems for CNAME > IP routes

### CODE REVIEW

**Comment by BClark09** [comment]
Also, royally screwed up the Diff with formatting changes. Really sorry about that!

**Comment by ThomDietrich** [comment]
>Also, royally screwed up the Diff with formatting changes. Really sorry about that!
Not a problem, do you know `w=1` ;)
https://github.com/ThomDietrich/openhabian/pull/27/files?w=1

**Comment by ThomDietrich** [comment]
Looks great! I'll merge and test this evening. Thanks!

Btw. I saw that you had to delete your fork and fork anew. Do you know that it's best to work in branches for PRs?

Again thanks for your contribution! I hope to see more from you in the future ;)

**Comment by BClark09** [comment]
I'm yet to take a self driven crash course in the wonders of git. So all of this is fairly new to me and have just been pushing buttons until something reasonable happens :see_no_evil: . Thanks a lot for the advice!

**Comment by ThomDietrich** [comment]
Hehehe. Been there, done that.

I found it very useful to use a GUI in the beginning. Many might argue that only by using the command line you will really understand the git internals but that's not what you are looking for in the beginning. I can recommend **GitKraken** as an easy to use and intuitive solution and my personal favorite is **SmartGit** (powerful, free, platform independent). I can not recommend the famous SourceTree as it will just throw the command line output at you and you'll have to figure out what's going on... in this case you are better off with the command line to begin with... But that is just my opinion!

Example for what you did here, maybe it's useful to kickstart your crash course:

* The first thing you do is **create a fork** of my repository on GitHub. Neither of the mentioned clients can do that for you (there are yet other tools out there).
* Next you would **clone your repository** in SmartGit and make sure to tick **"Create upstream remote"**. This way you will not only clone your repo but also see changes in the upstream repo, i.e. mine. (the upstream repo is just the name if a second "git remote")
* Now the first thing you should always do is (visit the "Log" view and) **create a new branch** on top of the latest commit.
* Next you can do your changes, commit to your new branch and at last **push your changes** back to your repository. GitHub will now invite you to **create a PR** based on that branch.
* After the **branch was merged** you probably want to bring your repository up to date (that's the point where you deleted your fork).
* **Pull** latest changes from the upstream repository master and **Push** them to your repository master. This way you will receive the merge commit and all other changes since you created your fork.
* You can now start to create yet another branch based on this one and start from the beginning.

After a while your Log could look like this:

2016-11-01 16_01_29-openhab-docs - log for

**Comment by BClark09** [comment]
Wow, thanks for the heads up. Hopefully my next PR will be the start of proper usage!

**Comment by ThomDietrich** [comment]
Amazing. Worked like a charm!
I added two improvements:

1. There are now three options: domain, static ip or no servername ("localhost")
2. Certbot will fail if port 80 of the RPi is not reachable. I've added a warning

I think we have reached a finished version of your feature. Amazing!! 🎆 🎉 I'll write a changelog posting the next few days.

**Comment by ThomDietrich** [comment]
Okay I've one last question, why this complicated?
```
$ cat /etc/cron.d/certrenew
24 7-23/12 * * * root certbot renew --quiet
```

**Comment by BClark09** [comment]
Nice additions! Certbot recommend performing an update check twice a day.  But let's encrypt ask that cron expressions are applied at a random time.  Since we're providing the cron,  then we wouldn't want to hardcode a timestamp,  otherwise a mass of raspberry pis will try to update at the same time.

**Comment by ThomDietrich** [comment]
I got the idea, I was just confused about the twice a day because last time I checked a certificate is valid three months and it's safe to check once per week... Seems this was updated https://certbot.eff.org/all-instructions/#debian-8-jessie-nginx

**Comment by BClark09** [comment]
Its just to stop systems being unavailable. 

Reading the docs again now,  I see that they do this with a debian install anyway.  We should probably our cron in this case from our script.

**Comment by ThomDietrich** [comment]
Oh, it does indeed
```shell
[11:12:12] pi@openHABianPiW66a:~$ cat /etc/cron.d/certbot
# /etc/cron.d/certbot: crontab entries for the certbot package
#
# Upstream recommends attempting renewal twice a day
#
# Eventually, this will be an opportunity to validate certificates
# haven't been revoked, etc.  Renewal will only occur if expiration
# is within 30 days.
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

0 */12 * * * root test -x /usr/bin/certbot && perl -e 'sleep int(rand(3600))' && certbot -q renew

[11:13:43] pi@openHABianPiW66a:~$ cat /etc/cron.d/certrenew
24 7-23/12 * * * root certbot renew --quiet
```

**Pull request merged**
