### PR TITLE
Added NGINX (auth/HTTPS) setup

### PR DESCRIPTION
**Pull request by BClark09**
Implements #12 and #11

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey Ben, great work! I've merged this right away to give it a test drive. (Testing right now)

I still have one requests...
Could you add the additional whiptail dialog to inform the user of the details before starting the process? I've done that in almost all routines to avoid accidental clicks... [see here](https://github.com/ThomDietrich/openhabian/blob/master/openhabian-setup.sh#L382-L390)

**Comment by ThomDietrich** [comment]
I've added a few small improvements to the printouts. Why did you decide to divide read and echo for the domain?

Another thing I just realized: One can not cancel while being in the prompts because I've trapped SIGINT. Would agree it would be a good idea to present all given information and ask for yet another confirmation before the setup process begins?

**Comment by ThomDietrich** [comment]
I encountered the first real problem: My domain is resolved though a CNAME entry pointing to a dyndns provider domain: `openhab.mydomain.de -> abcd.no-ip.biz -> 88.66.68.21`

Now `dig +short openhab.mydomain.de` produces:
```
abcd.no-ip.biz.
88.66.68.21
```

which as a string is not equal to my wanip ("88.66.68.21"). Sadly `dig +short openhab.mydomain.de A` will not solve this problem as a CNAME is always part of the answer (if you know better, let me know). How do you think we can solve this?

1. We could extend the command to always use the last line of the output
2. We could extend [the else part](https://github.com/ThomDietrich/openhabian/blob/master/openhabian-setup.sh#L784) with a "I don't care, just use the given domain" option.

**Comment by BClark09** [comment]
> Could you add the additional whiptail dialog to inform the user of the details before starting the process? I've done that in almost all routines to avoid accidental clicks

Sure thing!

---
> Why did you decide to divide read and echo for the domain?

Er.... Good question! I should have used a read prompt for this.

---
>Would agree it would be a good idea to present all given information and ask for yet another confirmation before the setup process begins?

Yes this would be a safe bet, otherwise some weird default nginx configurations might occur. I'll move the install of nginx to after this prompt too?

---
> CNAME entry pointing to a [..] domain

This is a normal way of doing this and for some reason didn't think of it! I don't think the "I don't care" option would be a good idea because if a domain can't eventually be resolved to the ip of the wan at the time of the setup, then this may cause problems with the proxy forwarding if the issue persists. Perhaps a better way of doing this is:
```
domainip=$(host $domain | awk '/has address/ { print $4 ; exit }')
```

**Comment by ThomDietrich** [comment]
> Yes this would be a safe bet, otherwise some weird default nginx configurations might occur. I'll move the install of nginx to after this prompt too?

As you think. Sounds reasonable. ;)

>I don't think the "I don't care" option would be a good idea because ...

I was thinking of the tech-savvy user, knowing what he's doing but maybe it's better to not tempt the normal end user to try and occupy a domain he doesn't own.

Why not `dig +short $domain |tail -1`? This should always return the A entry

**Comment by BClark09** [comment]
I've just been reading on this at it looks like the last line will always be an ip address. My hesitancy was if the last line was an ipv6 address if it ever becomes a default (rather than depending on AAAA type). But thinking about it changing $(dig +short myip.opendns.com @resolver1.opendns.com |tail -1) will always output the same IP and type.

**Comment by BClark09** [comment]
@ThomDietrich Would the input be better served through whiptail dialogue? That way we can keep to the same input type instead of suddenly shifting the user to reading the command line.

**Comment by ThomDietrich** [comment]
I've resorted to whiptail dialogs whenever possible to make things as "creamy" as possible for the end user but you already got your dialogs with read. So I would say it'ss totally up to you ;) As you know there is an example in the Karaf console function.

**Pull request merged**
